import React, {useState, useEffect} from "react";
import ActiveServerClients from "./ActiveServerClients";
import ActiveServerCompanies from "./ActiveServerCompanies";

import { CompanyObject, ClientObject } from "./WebInterfaces";
const APIBase:string = "http://localhost:3000"
export default function Info(props) {
    return(
        <div>
            <div>
                <table>
                    <thead>
                        <tr>
                            <th>Type</th>
                            <th>Freq</th>
                            <th>Number</th>
                        </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Date</td>
                        <td></td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>ClientInfo</td>
                        <td>Poll</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Comapny Info</td>
                        <td>Daily</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>Company Econ</td>
                        <td></td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>Company Stats</td>
                        <td>Weekly</td>
                        <td>4</td>
                    </tr>
                    <tr>
                        <td>Chat</td>
                        <td></td>
                        <td>5</td>
                    </tr>
                    <tr>
                        <td>Console</td>
                        <td></td>
                        <td>6</td>
                    </tr>
                    <tr>
                        <td>CMDNames</td>
                        <td></td>
                        <td>7</td>
                    </tr>
                    <tr>
                        <td>CMDLogging</td>
                        <td>Monthly</td>
                        <td>8</td>
                    </tr>
                    <tr>
                        <td>Gamescript</td>
                        <td></td>
                        <td>9</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>Quarterly</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>Anually</td>
                        <td>32</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>Automatic</td>
                        <td>64</td>
                    </tr>
                    </tbody>
                </table>
                <table>
                    <thead>
                        <tr>
                            <th>UpdateType</th>
                            <th>Poll</th>
                            <th>Daily</th>
                            <th>Weekly</th>
                            <th>Monthly</th>
                            <th>Quarterly</th>
                            <th>Anually</th>
                            <th>Automatic</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Date</td>
                            <td>Yes</td>
                            <td>Yes</td>
                            <td>Yes</td>
                            <td>Yes</td>
                            <td>Yes</td>
                            <td>No</td>
                            <td>No</td>
                        </tr>
                        <tr>
                            <td>Client Info</td>
                            <td>Yes</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>Yes</td>
                        </tr>
                        <tr>
                            <td>Company Info</td>
                            <td>Yes</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>Yes</td>
                        </tr>
                        <tr>
                            <td>Company Econ</td>
                            <td>Yes</td>
                            <td>No</td>
                            <td>Yes</td>
                            <td>Yes</td>
                            <td>Yes</td>
                            <td>Yes</td>
                            <td>No</td>
                        </tr>
                        <tr>
                            <td>Company Stats</td>
                            <td>Yes</td>
                            <td>No</td>
                            <td>Yes</td>
                            <td>Yes</td>
                            <td>Yes</td>
                            <td>Yes</td>
                            <td>No</td>
                        </tr>
                        <tr>
                            <td>Chat</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>Yes</td>
                        </tr>
                        <tr>
                            <td>Console</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>Yes</td>
                        </tr>
                        <tr>
                            <td>CMDNames</td>
                            <td>Yes</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                        </tr>
                        <tr>
                            <td>CMDLogging</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>Yes</td>
                        </tr>
                        <tr>
                            <td>GameScript</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>No</td>
                            <td>Yes</td>
                        </tr>
                    </tbody>
                </table>
                
            </div>
        </div>
    )
}
